### ISSUE TITLE
Header view as Gallery (scroll horizontal)

### ISSUE THREAD

**Issue by AladinWay** [AugustRush/ARSegmentPager#14]
First of all I really want to thank you for this great controller. Please can you help me to customize your controller basically I want to add two behaviors :
- Add a gallery in the header: so user can can scroll the header horizontally to browse images
-  After a certain negative offset (scroll down) the header expand the Gallery 

This two behaviors exists in this controller, See the third example please :

https://github.com/quemb/QMBParallaxScrollViewController

Anyone can help me, I may be a good feature for other users.

**Comment by AladinWay** [comment]
As a first step let's try to integrate the image pager (gallery) the controller mentioned above use this library of image gallery :

https://github.com/kimar/KIImagePager

I have tried to integrate it but without luck, the view remains white without  images any help please ?

**Comment by AugustRush** [comment]
Can you send me a demo with this bug?

发自我的 iPhone

**Comment by AladinWay** [comment]
Thank you very much for your fast replay and hope you can help me,  so please check this repo I have posted the code that I am working with here : 
https://github.com/AladinWay/ARSegmentPager

I have tried to integrate "KIImagePager" in the header but without luck, see that I was able to integrate it in the first view controller of the segmented control but not in the header, it's an example for you to see how  "KIImagePager" works 

also if you have the time it will be great if you check my other changes to replicate the "QMBParallaxScrollViewController" behavior  (expand if scroll down or tap) without luck also :(

1) Note that I have changed the segmented control to use  "HMSegmentedControl" instead of the default one 

2) I have changed the constraint of header to be public, because I am trying to expand the header if the user tap  the header or scroll down (stretch) the header after 100point for example but it does not work like in "QMBParallaxScrollViewController"

**Comment by AladinWay** [comment]
Update1:

I have managed to integrate the gallery in the header, but there is bugs: 

1) Try to scroll the gallery and let the displayed image the second or the third (not the first)
2) Try scroll the tableview or the scrollview (the content of segmented control)

result => the gallery will display the first image, not the current selected image

I have updated the repo : 

https://github.com/AladinWay/ARSegmentPager

**Comment by AladinWay** [comment]
Update 2 :

I guess in the method : 

-(void)observeValueForKeyPath:(NSString *)keyPath ofObject:(id)object change:(NSDictionary *)change context:(void *)context

updating the constraint will force the gallery to reset to it's first state and display the first image instead of the current one any idea to fix that ?

**Comment by AugustRush** [comment]
ok, let me see it, sorry for this,i'm In busy just now.

**Comment by AugustRush** [comment]
due to scroll the scrollView will call your custom Header to trigger methods: -(void)layoutSubviews;
and The KIImagePager override this methods with implimention:
- (void) layoutSubviews
  {
  for (UIView *view in self.subviews) {
      [view removeFromSuperview];
  }
  [self initialize];
  }

so, if you scroll the view , it will call this bug.

**Comment by AladinWay** [comment]
thank you for the update, actually I am trying to find a workaround, but the parameter "currentPage" keep resetting to 0 ! any suggestion ?

**Comment by AladinWay** [comment]
By the way I found a bug you didn't adjust the "ScrollIndicatorInsets" so the indicator is in the wrong place after you added the inset to the scrollview but not the scroll indicator just in your method 
"-(void)_layoutControllerWithController:(UIViewController<ARSegmentControllerDelegate> *)pageController"

add : 

[scrollView setScrollIndicatorInsets :UIEdgeInsetsMake(topInset, 0, bottomInset, 0)];

after :

[scrollView setContentInset:UIEdgeInsetsMake(topInset, 0, bottomInset, 0)];

**Comment by AugustRush** [comment]
I think the KIImagePager is not fit this situation, its implimention is not good. You should change another one. maybe just use a collectionView on custom header.

**Comment by AladinWay** [comment]
Thank you, I will try to find another implantation for the gallery, did you take a look and the feature of expand header view on click or on pull down, just click on the header or try to pull down the scrollview of the segmented control, any advice to have a better behavior, and sorry for taking form your time.
