### ISSUE TITLE
自定义headerview 滚动问题

### ISSUE THREAD

**Issue by 1xiaocainiao** [AugustRush/ARSegmentPager#15]
我自定义了一个headerview，包含有button，当我需要滑动headerview的时候，我看demo是重写了hittest方法，但是这样的话button的点击事件就失效了，有什么别的办法让header可以拖动,并且不影响button点击吗？感谢分享

**Comment by AugustRush** [comment]
如果滑动的时候时间被header拦截掉，那么header久无法滑动，因为滑动其实是下面的scrollView，所以按照你的意思来说。，你应该重写hitTest方法，判断如果触摸的是header本身就返回nil，如果是其他（比如它的子视图）就返回响应的view就好了

**Comment by 1xiaocainiao** [comment]
恩，也只能这样了，谢谢解答
