### ISSUE TITLE
最近有时间看了po主的源码，发现一个实现上的问题，讨论一下

### ISSUE THREAD

**Issue by itdongbaojun** [AugustRush/ARSegmentPager#16]
首先非常感谢@AugustRush开源了这么好用的框架，最近有时间看了一下源码，主要的实现逻辑是在kvo的-(void)observeValueForKeyPath:(NSString *)keyPath ofObject:(id)object change:(NSDictionary *)change context:(void *)context的这个方法里，根据scrollView的偏移量来改变headerView的高度约束，这样会导致一个小问题，就是在自定义headerView的时候，headerView中子view的约束如果不是和bottom关联而是和top关联的就会出现一些小问题（或者自定义headerView没有使用约束布局）。不知道是否能通过修改headerView的top约束来实现类似的效果。

**Comment by AugustRush** [comment]
当然可以的，autolayout本来就是相对约束，根据top和bottom只是计算方法上的不同，如果用根据top来算的话约束改变下是可以解决这个问题的
