### ISSUE TITLE
自定义了head之后  滑动head事件不能用了

### ISSUE THREAD

**Issue by GeekZP** [AugustRush/ARSegmentPager#17]
自定义了head之后  滑动head事件不能用了，这个有什么解决办法么

**Comment by AugustRush** [comment]
这个demo里有自定义header的，你可以看看

发自我的 iPhone

**Comment by GeekZP** [comment]
对  是demo里的   但是我手指拉动头部的图片无法拉动，没自定义的那个是可以的
