### ISSUE TITLE
怎么在headerView增加refreshControl，来刷新下面的tableview

### ISSUE THREAD

**Issue by magiccash** [AugustRush/ARSegmentPager#19]

**Comment by AugustRush** [comment]
看你具体的需求了，你要做成什么样子?

**Comment by magiccash** [comment]
我想在customheader里面加个动画，通过下面tableview controller 的下拉控制动画启动和并发起网络请求，请求成功后reloadData,但是这样contentoffset会设置成0，界面会发生抖动。有什么好的方法解决吗？

**Comment by AugustRush** [comment]
reloadData不会把contentOffset设置成0吧？你是不是理解错了

**Comment by magiccash** [comment]
不好意思，说错了，contentOffset设置回了最初的值，但是我还处于下拉的的状态，所以回弹了下

**Comment by AugustRush** [comment]
这个 。。。 还是不太理解你说的问题，能不能详细描述下，或者给个demo什么的？

**Comment by yangy4444** [comment]
同问啊，能否在这个界面的头部，或者下面tableview 加上下拉刷新。

**Comment by AugustRush** [comment]
可以啊，你直接用INSPullToRefresh吧，省时间

**Comment by yangy4444** [comment]
用MJRefesh加在下面的tableview上面，下拉的时候头部跟着变大。。。。

**Comment by AugustRush** [comment]
截个图看看

**Comment by huiyumiao** [comment]
用MJRefesh刷新下面的tableview，刷新后ARSegmentView部分会向上移动与MJRefeshHeader等高的距离，然后向上滑动tableview至MJRefeshHeader被顶出屏幕后又恢复正常了；或者是切换segment标签也能恢复正常。请问该怎么解决呢

**Comment by AugustRush** [comment]
求有问题的demo，虽然大概知道问题出在哪里，但是还是想具体看看根源

**Comment by huiyumiao** [comment]
https://github.com/huiyumiao/ARSegmentControllerDemo.git
只是简单的在您原来demo基础上添加了MJRefresh

**Comment by huiyumiao** [comment]
大神，这个问题解决了吗？

**Comment by AugustRush** [comment]
@magiccash @yangy4444 @huiyumiao 我刚刚commit了一次在master分支，可以去看看，帮忙测试下是否该问题已经解决。

**Comment by huiyumiao** [comment]
好的，非常感谢

**Comment by huiyumiao** [comment]
我遇到的那个问题已经OK了。但又发现了一个小问题，就是在‘push’进去的那个页面中快速滑动下面的tableView时上面的header会有比较明细的跳动（这个其实不影响使用）。总之非常感谢！！！

**Comment by huiyumiao** [comment]
不好意思啊，刚刚用真机试了效果，没有发现跳动的现象。 很赞的控件

**Comment by AugustRush** [comment]
不用客气，其实跳动是有的，跟你的滑动速度有关系，快的话还是能看到，不过暂时没有什么好办法解决
