### ISSUE TITLE
示例demo header显示错乱

### ISSUE THREAD

**Issue by TLcv** [AugustRush/ARSegmentPager#22]
点击push按钮，不拖动然后 第一个列表跳转到第三个列表，，第三列加载header显示错乱

**Comment by AugustRush** [comment]
好了，你看下

**Comment by TLcv** [comment]
@AugustRush 恩，已解决。提两点意见：
1:header处于下面时往下拖动会有轻微的回弹,
2: headerView的收缩可以改为top值的修改，这样的话可以不局限于headerView仅仅设置为图片，自定义的view也同样可以使用

**Comment by AugustRush** [comment]
嗯，谢谢建议，目前回弹是因为设置了freezenHeaderWhenReachMaxHeaderHeight为YES，改为NO就会随着拉伸了（跟滑动的速度有关）。2.headerVIew现在可以自定义，只需要重载- (UIView<ARSegmentPageControllerHeaderProtocol> *)customHeaderView;这个方法即可，不过在布局约束上要做一些处理。不过正打算写一个swift的，改善下现在的实现。
