### ISSUE TITLE
Add to cocoapods trunk

### ISSUE THREAD

**Issue by maxkramer** [AugustRush/ARSegmentPager#25]
Hi,

Your podspec seems to be fine, but the spec itself hasn't been added to cocoapod trunk and is therefore results in an unable to find 'ARSegmentPage' pod when trying to install it.

Proof: https://cocoapods.org/?q=arsegmentpager

Cheers,
Max.

**Comment by AugustRush** [comment]
OK, I have added it to cocoapods , you  can check it and  'pod search' to find it 
<img width="524" alt="9fad3fccd3006cfd370082ba8c7d3745" src="https://cloud.githubusercontent.com/assets/6881916/13737774/cab89aac-e9fa-11e5-96ca-fa13f245f176.png">
