### ISSUE TITLE
Cannot remove an observer

### ISSUE THREAD

**Issue by ronaldalfaro** [AugustRush/ARSegmentPager#28]
Hi! when a function with this code is called:

self.publicProfileVC = [[PublicProfileVC alloc]  init];
[self.navController pushViewController:self.publicProfileVC animated:YES];

 I'm getting this error:
Uncaught exception: Cannot remove an observer <PublicProfileVC 0x182590f0> for the key path "segmentTopInset" from <PublicProfileVC 0x182590f0> because it is not registered as an observer.

What may be causing this error? thanks!

**Comment by AugustRush** [comment]
This is very strange, i need detail info so that i can figure it out.
