### ISSUE TITLE
No older version and can not find ARSegmentView object property in library

### ISSUE THREAD

**Issue by hanweixing** [AugustRush/ARSegmentPager#33]
I import this library in my project last year, it worked well. But now when i running 'pod update' command, the library update and it crashes. 
The error is that my project could not find the ARSegmentView object property of the UIViewController. I found that the latest library set this property private, i can not get the property directly.
So i suggest that author should keep older version, otherwise it would take much time to modify the project to adjust the latest library.

**Comment by hanweixing** [comment]
Because there is no older version, i decided to manage the library manually. So far, it runs well too. But it is old version which ARSegmentView object property in UIViewController is public.

**Comment by AugustRush** [comment]
Yes, i got it, i have make 'segmentView' to public , you can use cocoapods to update it.
