### ISSUE TITLE
iOS11切换事件不响应

### ISSUE THREAD

**Issue by JKshared92** [AugustRush/ARSegmentPager#38]
在iOS11的时候，试图加载完之后，会在segmentView上加一个UIToolBar，就覆盖掉了本身的点击事件，没有人遇到吗？？？

**Comment by AugustRush** [comment]
噢 我试了下 iOS11 问题还挺多的。。。

**Comment by JKshared92** [comment]
我也不知道，昨天更新适配，发现点不了，然后就打开视图层看了一下，不知道为什么segmentView上有一个view，就把点击事件遮盖了
不是iOS11就是正常的，你没有遇到这个吗？

**Comment by AugustRush** [comment]
我准备改一下，或者写一个新的。。。

**Comment by JKshared92** [comment]
好吧，重新写一个也不错，我看怎么弄了先适配吧

**Comment by AugustRush** [comment]
我刚刚大致改了下，你看一下是否好了？

**Comment by aiancu** [comment]
Any way we can move this fix to the actual pod? The only updated files are the example copy of the pod.
