### ISSUE TITLE
While showing inside a navigation controller how to deal with Navigation Bar?

### ISSUE THREAD

**Issue by kidsid49** [AugustRush/ARSegmentPager#6]
My profile view controller is embedded inside the Navigation controller and when I push pager  its shows up with coloured navigation bar. While in demo its transparent one. How one can achieve that?

**Comment by AugustRush** [comment]
You can use ARSegmentPageController like a UIViewController , subclass it like a common UIViewController , you can do anything in it.

**Comment by kidsid49** [comment]
But I am curious how you are achieving this in your demo. Because viewcontroller is not subclass of ARSegmentPageController and it is embedded in UINavigationController. How you managed to get transparent Navigation Bar so that the Header Image below is visible?

**Comment by kidsid49** [comment]
Ok I found the solution. 

 [self.navigationBar setBackgroundImage:[UIImage new]
                         forBarMetrics:UIBarMetricsDefault];
self.navigationBar.shadowImage = [UIImage new];
self.navigationBar.translucent = YES;
self.navigationController.navigationBar.tintColor = [UIColor clearColor];
self.navigationController.navigationBar.backgroundColor = [UIColor clearColor];

**Comment by AugustRush** [comment]
yeah, you are right 😄
