### ISSUE TITLE
After subclassing ARSegmentPageController for customising header KVO for "segmentToInset" doesn't work?

### ISSUE THREAD

**Issue by kidsid49** [AugustRush/ARSegmentPager#7]
I added this line in my viewDidLoad :  
[self addObserver:self forKeyPath:@"segmentToInset" options:NSKeyValueObservingOptionNew context:NULL];

But when call comes here on this line
CGFloat topInset = [change[NSKeyValueChangeNewKey] floatValue];

Its crashes with this message.
-[NSConcreteValue floatValue]: unrecognized selector sent to instance 0x7fc7ebed4aa0

Can you explain what I am doing wrong here? Or can you put your customised header code in sample project that would really help.

**Comment by AugustRush** [comment]
It's 'segmentTopInset' ,not 'segmentToInset'.

发自我的 iPhone

**Comment by kidsid49** [comment]
[self addObserver:self forKeyPath:@"segmentTopInset" options:NSKeyValueObservingOptionNew context:NULL];

doesn't help. Its same crash. In-fact  I added "segmentToInset" by looking into your sample project only.
It would really help if you can write steps to use customise header in your documentation.

**Comment by AugustRush** [comment]
Can you paste your code here? 

发自我的 iPhone

**Comment by kidsid49** [comment]
in .h file its
@interface GWProfileViewController : ARSegmentPageController

and then in viewDidLoad 

```
[self addObserver:self forKeyPath:@"segmentTopInset" options:NSKeyValueObservingOptionNew context:NULL];
```

and then KVO:-

-(void)observeValueForKeyPath:(NSString *)keyPath ofObject:(id)object change:(NSDictionary *)change context:(void *)context {

```
CGFloat topInset = [change[NSKeyValueChangeNewKey] floatValue];
NSLog(@"top inset is %f",topInset);

if (topInset <= self.pager.segmentMiniTopInset) {
    self.pager.title = @"Siddarth Chaturvedi";
    self.pager.headerView.imageView.image = self.blurImage;
}else{
    self.pager.title = nil;
    self.pager.headerView.imageView.image = self.defaultImage;
    //self.blurImage = [self.pager.headerView.imageView.image applyDarkEffect];
}
```

}

App crashes on method first line :  
CGFloat topInset = [change[NSKeyValueChangeNewKey] floatValue];

**Comment by kidsid49** [comment]
@AugustRush able to figure it out whats happening?

**Comment by AugustRush** [comment]
Did you call [Super viewDidLoad]? Or,can you pasted more details codes?

发自我的 iPhone

**Comment by kidsid49** [comment]
@AugustRush Yeah! I will. But can you add the custom header example in your sample project? That would helpful for anyone who is trying to use this :-)

**Comment by AugustRush** [comment]
Okay,I will add a demo in a while.

发自我的 iPhone

**Comment by AugustRush** [comment]
You can check it out 

发自我的 iPhone

**Comment by kidsid49** [comment]
@AugustRush Thanks!
